### ISSUE TITLE
 contact email 

### ISSUE THREAD

**Issue by Xllllll521** [haakontn/QuaternionAzimuthal#1]
I would like to express my gratitude for sharing your valuable articles on GitHub. They have had a profound impact on me and have been a valuable resource for my learning.I have some questions related to your articles and would appreciate the opportunity to consult with you.  I was wondering if it would be possible to obtain your contact email so that I can provide more detailed information about my inquiries and engage in further discussion. If it's convenient for you, I would greatly appreciate it.

**Comment by haakontn** [comment]
Please feel free to contact me at my university email address. The email address is given in my first author publication linked in the references section of the README.md (direct link to the paper: https://www.sciencedirect.com/science/article/pii/S0010218021003084). Click on the email symbol in the author list, or find it at the bottom of the first page in the PDF (open access).

Sometimes the university wide email filter is a bit restrictive, so I will close this issue after I receive your email as a delivery receipt.

**Comment by Xllllll521** [comment]
I would like to express my appreciation for the code you've provided, which appears to be theoretically sound. However, I am interested in conducting a traditional verification process and would like to inquire if you have access to the code used by Nicholas A. Worth in "Effect of equivalence ratio on the modal dynamics of azimuthal combustion instabilities."

----- 原始邮件 -----
发件人: "haakontn" ***@***.***>
收件人: "haakontn/QuaternionAzimuthal" ***@***.***>
抄送: "Xllllll521" ***@***.***>, "Author" ***@***.***>
发送时间: 星期二, 2024年 1 月 30日 下午 7:14:40
主题: Re: [haakontn/QuaternionAzimuthal]  contact email  (Issue #1)

Closed #1 as completed.

-- 
Reply to this email directly or view it on GitHub:
https://github.com/haakontn/QuaternionAzimuthal/issues/1#event-11640216889

**Comment by haakontn** [comment]
Unfortunately I don't have access to that. Please see my longer answer on email
